# Use Node.js 14 as the base image
FROM node:21.1

# Set the working directory
WORKDIR /app

# Install create-react-app globally
RUN npm install -g create-react-app

# Expose port 3000
EXPOSE 3000

# Run the app
CMD ["/bin/bash"]


