# Use Node.js 14 as the base image
FROM node:21.1

# Set the working directory
WORKDIR /app

# Expose port 3000
EXPOSE 3000

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Run the app
CMD ["/bin/bash"]


