version: "3.9"
services:
 react1:
  build: ./Frontend
  container_name: r1
  ports:
   - "80:5173"
  volumes:
   - ./Frontend:/app
  stdin_open: true
  tty: true
  environment:
      - WATCHPACK_POLLING=true

 node1:
  build: ./Backend
  container_name: n1
  ports:
   - "5000:5000"
  volumes:
   - ./Backend:/server
  stdin_open: true
  tty: true
  environment:
      - WATCHPACK_POLLING=true

 couchdb1:
  image: couchdb:3.2.0
  container_name: cdb1
  ports:
   - "5984:5984"
  volumes:
   - ./couchdb:/opt/couchdb/data
  environment:
   - COUCHDB_USER=admin
   - COUCHDB_PASSWORD=pwd